// <auto-generated />
using System;
using EventApi.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace agilt_projekt.api.Data.Migrations
{
    [DbContext(typeof(EventApiContext))]
    [Migration("20230920174733_OneToManyManyToMany")]
    partial class OneToManyManyToMany
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.11");

            modelBuilder.Entity("AttendentModelEventModel", b =>
                {
                    b.Property<int>("AttendentsAttendentId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("EventListEventId")
                        .HasColumnType("INTEGER");

                    b.HasKey("AttendentsAttendentId", "EventListEventId");

                    b.HasIndex("EventListEventId");

                    b.ToTable("AttendentModelEventModel");
                });

            modelBuilder.Entity("EventApi.Models.AttendentModel", b =>
                {
                    b.Property<int>("AttendentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("EventId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("PhoneNumber")
                        .HasColumnType("INTEGER");

                    b.HasKey("AttendentId");

                    b.ToTable("Attendents");
                });

            modelBuilder.Entity("EventApi.Models.EventModel", b =>
                {
                    b.Property<int>("EventId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("EventName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("TEXT");

                    b.HasKey("EventId");

                    b.ToTable("Events");
                });

            modelBuilder.Entity("AttendentModelEventModel", b =>
                {
                    b.HasOne("EventApi.Models.AttendentModel", null)
                        .WithMany()
                        .HasForeignKey("AttendentsAttendentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EventApi.Models.EventModel", null)
                        .WithMany()
                        .HasForeignKey("EventListEventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
